### ISSUE TITLE
[PE-D][Tester B] Clear feature does not 100% follow the input format.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-4/tp#115]
The clear command is stated in the User Guide as `clear`. However when I gave it other inputs, it still cleared my address book.

Given Input: `clear 44`
Expected Output: error, wrong format
Actual Output: Clears the entire address book

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: TheodoreKooo/ped#8

**Comment by STELLA-LYE** [comment]
patched in UG
