### ISSUE TITLE
[PE-D][Tester B] The Filter command does not show that the group does not exist.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-4/tp#117]
After clearing the address book, i tried to use the filter command and it returned `0 students listed`. This may become problematic when there are lots of groups to keep track of and using a filter command like this might mislead the user into thinking that the group has already been added but there are no students assigned to that group.

Given input: Filter TUT01 (The group TUT01 does not exist)
Output: `0 students listed!`

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TheodoreKooo/ped#10

**Comment by STELLA-LYE** [comment]
patched in UG
